<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = $this->getProducts();

        foreach ($products as $product) {
            Product::create($product);
        }
    }

    private function getProducts(): array
    {
        return [
            ['name' => 'Call of Duty WW2', 'image' => 'images/cod_ww2.jpg', 'description' => 'Tapasztald meg a második világháború ikonikus csatáit ebben az epikus first-person shooter játékban. Játszd el a híres hadműveleteket és alakítsd a történelem menetét.', 'platform' => 'PC/Console', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2017, 'prices' => json_encode([['seller' => 'GameShop', 'price' => 15999, 'rating' => 4.8], ['seller' => 'DigitalGames', 'price' => 16200, 'rating' => 4.5], ['seller' => 'TechStore', 'price' => 15800, 'rating' => 4.7]])],
            ['name' => 'Dead by Daylight', 'image' => 'images/dbd.jpg', 'description' => 'Egy multiplayer horror játék, ahol túlélők próbálnak megszökni egy gyilkos elől. Játszd a túlélő vagy a gyilkos szerepét izgalmas, feszült mérkőzésekben.', 'platform' => 'Multiplatform', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2016, 'prices' => json_encode([['seller' => 'HorrorHub', 'price' => 19999, 'rating' => 4.6], ['seller' => 'GameWorld', 'price' => 20100, 'rating' => 4.4], ['seller' => 'DigitalGames', 'price' => 19800, 'rating' => 4.9]])],
            ['name' => 'The Last of Us Part I', 'image' => 'images/lou_part1.jpg', 'description' => 'Joel és Ellie története egy poszt-apokaliptikus világban. Ez az érzelmes, akciódús játék a túlélésről és az emberi kapcsolatokról szól.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2013, 'prices' => json_encode([['seller' => 'SonyStore', 'price' => 8999, 'rating' => 4.9], ['seller' => 'GameShop', 'price' => 9200, 'rating' => 4.7], ['seller' => 'TechStore', 'price' => 8800, 'rating' => 4.8]])],
            ['name' => 'Battlefield 6', 'image' => 'images/bf_6.jpg', 'description' => 'A Battlefield sorozat legújabb része hatalmas, pusztító csatákkal. Tapasztald meg a modern háború káoszát nagy létszámú multiplayer módokban.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2021, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 3999, 'rating' => 4.5], ['seller' => 'GameWorld', 'price' => 4100, 'rating' => 4.3], ['seller' => 'DigitalGames', 'price' => 3950, 'rating' => 4.6]])],
            ['name' => 'FC 26', 'image' => 'images/fc_26.jpg', 'description' => 'A FIFA sorozat új kiadása, ahol irányíthatod kedvenc csapataidat vagy létrehozhatsz saját játékost. Élvezd a valósághű focit 1 hónapos előfizetéssel.', 'platform' => 'Multiplatform', 'genre' => 'Sports', 'category' => 'console_games', 'release_year' => 2025, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 3500, 'rating' => 4.7], ['seller' => 'SportGames', 'price' => 3600, 'rating' => 4.4], ['seller' => 'GameShop', 'price' => 3450, 'rating' => 4.8]])],
            ['name' => 'Red Dead Redemption 2', 'image' => 'images/rdr_2.jpg', 'description' => 'Arthur Morgan kalandjai az amerikai vadnyugaton. Ez az open-world játék a bűnözés, a túlélés és a moralitás témáit járja körül.', 'platform' => 'Multiplatform', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2018, 'prices' => json_encode([['seller' => 'Rockstar Store', 'price' => 4999, 'rating' => 4.9], ['seller' => 'GameWorld', 'price' => 5100, 'rating' => 4.6], ['seller' => 'DigitalGames', 'price' => 4950, 'rating' => 4.8]])],
            ['name' => 'YouCam', 'image' => 'images/youcam.jpg', 'description' => 'Professzionális fényképszerkesztő szoftver. Szépítsd ki képeidet, távolítsd el a háttért és alkosd meg a tökéletes selfie-t.', 'platform' => 'PC', 'genre' => 'Software', 'category' => 'software', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'CyberLink', 'price' => 12999, 'rating' => 4.5], ['seller' => 'SoftwareHub', 'price' => 13200, 'rating' => 4.3], ['seller' => 'TechStore', 'price' => 12800, 'rating' => 4.7]])],
            ['name' => 'McAfee', 'image' => 'images/mcafee.jpg', 'description' => 'Biztonságos vírusvédelmi szoftver. Védje számítógépét a vírusoktól, malware-tól és online fenyegetésektől 1 évig.', 'platform' => 'PC', 'genre' => 'Security', 'category' => 'software', 'release_year' => 2024, 'prices' => json_encode([['seller' => 'McAfee Official', 'price' => 9999, 'rating' => 4.6], ['seller' => 'SecurityPro', 'price' => 10100, 'rating' => 4.4], ['seller' => 'TechStore', 'price' => 9800, 'rating' => 4.8]])],
            ['name' => 'Backup', 'image' => 'images/backup.jpg', 'description' => 'Automatikus adatmentő szoftver. Biztosítsd adataidat a veszteség ellen és tárold őket biztonságosan a felhőben.', 'platform' => 'PC', 'genre' => 'Utility', 'category' => 'software', 'release_year' => 2024, 'prices' => json_encode([['seller' => 'Backup Solutions', 'price' => 2999, 'rating' => 4.4], ['seller' => 'SoftwareHub', 'price' => 3100, 'rating' => 4.2], ['seller' => 'TechStore', 'price' => 2950, 'rating' => 4.6]])],
            ['name' => 'Grand Theft Auto V', 'image' => 'images/gta_v.jpg', 'description' => 'Los Santos városában játszódó open-world akció játék. Lopj autót, kövess el bűncselekményeket és élvezd a szabadságot.', 'platform' => 'Multiplatform', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2013, 'prices' => json_encode([['seller' => 'Rockstar Store', 'price' => 2999, 'rating' => 4.8], ['seller' => 'GameWorld', 'price' => 3100, 'rating' => 4.6], ['seller' => 'DigitalGames', 'price' => 2950, 'rating' => 4.9]])],
            ['name' => 'Minecraft', 'image' => 'images/minecraft.jpg', 'description' => 'Kreatív sandbox játék, ahol építhetsz, bányászolhatsz és túlélhetsz egy blokkos világban. Végtelen lehetőségek.', 'platform' => 'Multiplatform', 'genre' => 'Sandbox', 'category' => 'pc_games', 'release_year' => 2011, 'prices' => json_encode([['seller' => 'Mojang', 'price' => 4999, 'rating' => 4.7], ['seller' => 'GameShop', 'price' => 5100, 'rating' => 4.5], ['seller' => 'DigitalGames', 'price' => 4950, 'rating' => 4.8]])],
            ['name' => 'Minecraft Xbox', 'image' => 'images/minecraft_xbox.jpg', 'description' => 'Kreatív sandbox játék Xbox-on. Építs, bányász és túlélj.', 'platform' => 'Xbox', 'genre' => 'Sandbox', 'category' => 'console_games', 'release_year' => 2012, 'prices' => json_encode([['seller' => 'Microsoft', 'price' => 2999, 'rating' => 4.6]])],

            ['name' => 'The Witcher 3: Wild Hunt', 'image' => 'images/witcher_3.jpg', 'description' => 'Geralt of Rivia kalandjai egy fantasy világban. Vadászd a szörnyeket, hozd meg a nehéz döntéseket.', 'platform' => 'Multiplatform', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2015, 'prices' => json_encode([['seller' => 'CD Projekt', 'price' => 1999, 'rating' => 4.9], ['seller' => 'GameShop', 'price' => 2100, 'rating' => 4.7], ['seller' => 'DigitalGames', 'price' => 1950, 'rating' => 4.8]])],
            ['name' => 'Cyberpunk 2077', 'image' => 'images/cyberpunk.jpg', 'description' => 'Night City-ben játszódó RPG, ahol a jövőben élsz. Válassz utadat a bűnözők, vállalatok és hackerek világában.', 'platform' => 'Multiplatform', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'CD Projekt', 'price' => 3999, 'rating' => 4.2], ['seller' => 'GameWorld', 'price' => 4100, 'rating' => 4.0], ['seller' => 'DigitalGames', 'price' => 3950, 'rating' => 4.3]])],
            ['name' => 'Among Us', 'image' => 'images/amoungus.jpg', 'description' => 'Multiplayer játék, ahol űrhajósok között vannak imposterok. Találd ki ki a csaló és mentsd meg a hajót.', 'platform' => 'Multiplatform', 'genre' => 'Party', 'category' => 'pc_games', 'release_year' => 2018, 'prices' => json_encode([['seller' => 'Innersloth', 'price' => 499, 'rating' => 4.5], ['seller' => 'GameShop', 'price' => 600, 'rating' => 4.3]])],





            ['name' => 'The Sims 4', 'image' => 'images/sims_4.jpg', 'description' => 'Életszimulátor játék, ahol irányítod a simsek életét. Építs házat, neveld az állatokat és építs karriert.', 'platform' => 'PC', 'genre' => 'Simulation', 'category' => 'pc_games', 'release_year' => 2014, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 1999, 'rating' => 4.5], ['seller' => 'GameShop', 'price' => 2100, 'rating' => 4.3]])],
            ['name' => 'Stardew Valley', 'image' => 'images/stardew_valley.jpg', 'description' => 'Farm szimulátor játék. Műveld a földet, neveld az állatokat és építs kapcsolatokat.', 'platform' => 'Multiplatform', 'genre' => 'Simulation', 'category' => 'pc_games', 'release_year' => 2016, 'prices' => json_encode([['seller' => 'ConcernedApe', 'price' => 1499, 'rating' => 4.8], ['seller' => 'GameWorld', 'price' => 1600, 'rating' => 4.6]])],
            ['name' => 'Civilization VI', 'image' => 'images/civilization_6.jpg', 'description' => 'Stratégiai játék, ahol civilizációt építesz az ókortól a modern korig.', 'platform' => 'Multiplatform', 'genre' => 'Strategy', 'category' => 'pc_games', 'release_year' => 2016, 'prices' => json_encode([['seller' => '2K Games', 'price' => 2999, 'rating' => 4.7], ['seller' => 'GameShop', 'price' => 3100, 'rating' => 4.5]])],
            ['name' => 'FIFA 23', 'image' => 'images/fifa_23.jpg', 'description' => 'Foci szimulátor játék. Játszd a mérkőzéseket, irányítsd a csapatokat.', 'platform' => 'Multiplatform', 'genre' => 'Sports', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 4999, 'rating' => 4.4], ['seller' => 'SportGames', 'price' => 5100, 'rating' => 4.2]])],
            ['name' => 'NBA 2K24', 'image' => 'images/nba_2k24.jpg', 'description' => 'Kosárlabda szimulátor. Játszd a NBA mérkőzéseket, építs csapatot.', 'platform' => 'Multiplatform', 'genre' => 'Sports', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => '2K Games', 'price' => 5999, 'rating' => 4.6], ['seller' => 'SportGames', 'price' => 6100, 'rating' => 4.4]])],
            ['name' => 'Assassin\'s Creed Valhalla', 'image' => 'images/ac_valhalla.jpg', 'description' => 'Viking kalandok Angliában. Harcolj, építs települést és fedezd fel a történelmet.', 'platform' => 'Multiplatform', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Ubisoft', 'price' => 3999, 'rating' => 4.5], ['seller' => 'GameWorld', 'price' => 4100, 'rating' => 4.3]])],
            ['name' => 'Spider-Man 2', 'image' => 'images/spiderman_2.jpg', 'description' => 'Peter Parker és Miles Morales kalandjai New Yorkban. Harcolj a bűnözők ellen.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'SonyStore', 'price' => 6999, 'rating' => 4.8], ['seller' => 'GameShop', 'price' => 7100, 'rating' => 4.6]])],
            ['name' => 'Hogwarts Legacy', 'image' => 'images/hogwarts_legacy.jpg', 'description' => 'Harry Potter világában játszódó RPG. Tanulj varázslatot, fedezd fel a kastélyt.', 'platform' => 'Multiplatform', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Warner Bros', 'price' => 4999, 'rating' => 4.7], ['seller' => 'GameWorld', 'price' => 5100, 'rating' => 4.5]])],
            ['name' => 'Elden Ring', 'image' => 'images/elden_ring.jpg', 'description' => 'Dark Souls stílusú akció RPG. Harcolj szörnyekkel, fedezd fel a világot.', 'platform' => 'Multiplatform', 'genre' => 'Action RPG', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'Bandai Namco', 'price' => 5999, 'rating' => 4.9], ['seller' => 'GameShop', 'price' => 6100, 'rating' => 4.7]])],
            ['name' => 'God of War Ragnarök', 'image' => 'images/gow_ragnarök.jpg', 'description' => 'Kratos és Atreus kalandjai a skandináv mitológiában. Epikus történet és harc.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'SonyStore', 'price' => 6999, 'rating' => 4.9], ['seller' => 'GameWorld', 'price' => 7100, 'rating' => 4.7]])],

            ['name' => 'Microsoft Office 365', 'image' => 'images/microsoft_office_365.jpg', 'description' => 'Irodai szoftvercsomag. Word, Excel, PowerPoint és több.', 'platform' => 'PC', 'genre' => 'Software', 'category' => 'software', 'release_year' => 2011, 'prices' => json_encode([['seller' => 'Microsoft', 'price' => 9999, 'rating' => 4.6]])],
            ['name' => 'Norton Antivirus', 'image' => 'images/Norton.jpg', 'description' => 'Vírusvédelmi szoftver. Védelmet nyújt vírusok és online fenyegetések ellen.', 'platform' => 'PC', 'genre' => 'Security', 'category' => 'software', 'release_year' => 1991, 'prices' => json_encode([['seller' => 'Norton', 'price' => 4999, 'rating' => 4.5], ['seller' => 'SecurityPro', 'price' => 5100, 'rating' => 4.3]])],





            ['name' => 'Spotify Premium', 'image' => 'images/spotify.jpg', 'description' => 'Zenei streaming szolgáltatás. Hallgass millió zenét reklámmentesen.', 'platform' => 'Multiplatform', 'genre' => 'Entertainment', 'category' => 'game_subscriptions', 'release_year' => 2008, 'prices' => json_encode([['seller' => 'Spotify', 'price' => 999, 'rating' => 4.7]])],
            ['name' => 'Netflix', 'image' => 'images/netflix.jpg', 'description' => 'Videostreaming szolgáltatás. Nézz filmeket és sorozatokat.', 'platform' => 'Multiplatform', 'genre' => 'Entertainment', 'category' => 'game_subscriptions', 'release_year' => 2007, 'prices' => json_encode([['seller' => 'Netflix', 'price' => 1499, 'rating' => 4.5]])],

            ['name' => 'YouTube Premium', 'image' => 'images/yt.jpg', 'description' => 'Videómegosztó szolgáltatás prémium verziója. Reklámmentes nézés.', 'platform' => 'Multiplatform', 'genre' => 'Entertainment', 'category' => 'game_subscriptions', 'release_year' => 2014, 'prices' => json_encode([['seller' => 'Google', 'price' => 1399, 'rating' => 4.3]])],
            ['name' => 'Assassin\'s Creed Valhalla', 'image' => 'images/ac_valhalla.jpg', 'description' => 'Viking kalandok a középkorban. Építs birodalmat és harcolj.', 'platform' => 'PC', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Ubisoft', 'price' => 5999, 'rating' => 4.5]])],
            ['name' => 'Alien: Isolation', 'image' => 'images/alien_ isolation.jpg', 'description' => 'Horror játék a Xenomorph-mal. Túlélés egy űrállomáson.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2014, 'prices' => json_encode([['seller' => 'Sega', 'price' => 2999, 'rating' => 4.6]])],
            ['name' => 'Alien: Dark Descent', 'image' => 'images/alien_dark_descent.png', 'description' => 'Stratégiai horror játék az Alien univerzumban.', 'platform' => 'PC', 'genre' => 'Strategy', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Focus Entertainment', 'price' => 4999, 'rating' => 4.4]])],
            ['name' => 'Arc Raiders', 'image' => 'images/arc_raiders.jpg', 'description' => 'Akció játék intenzív harcokkal.', 'platform' => 'PC', 'genre' => 'Action', 'category' => 'pc_games', 'release_year' => 2024, 'prices' => json_encode([['seller' => 'Embark Studios', 'price' => 3999, 'rating' => 4.2]])],
            ['name' => 'ARK: Survival Ascended', 'image' => 'images/ark_survival_ascended.jpg', 'description' => 'Túlélő játék dinoszauruszokkal. Építs és harcolj.', 'platform' => 'PC', 'genre' => 'Survival', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Studio Wildcard', 'price' => 4999, 'rating' => 4.3]])],
            ['name' => 'Aliens vs. Predator', 'image' => 'images/avp.jpg', 'description' => 'Kereszttűz az Alien, Predator és Marine-ok között.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2010, 'prices' => json_encode([['seller' => 'Sega', 'price' => 1999, 'rating' => 4.1]])],
            ['name' => 'Back 4 Blood', 'image' => 'images/back_4_blood.jpg', 'description' => 'Kooperatív shooter zombik ellen.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2021, 'prices' => json_encode([['seller' => 'Turtle Rock', 'price' => 3999, 'rating' => 4.0]])],
            ['name' => 'Batman: Arkham Asylum', 'image' => 'images/batman_arkham.jpg', 'description' => 'Batman kalandjai az Arkham elmegyógyintézetben.', 'platform' => 'PC', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2009, 'prices' => json_encode([['seller' => 'Rocksteady', 'price' => 2999, 'rating' => 4.8]])],
            ['name' => 'Battlefield 1', 'image' => 'images/bf_1.jpg', 'description' => 'Az első világháború epikus csatái.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2016, 'prices' => json_encode([['seller' => 'EA DICE', 'price' => 3999, 'rating' => 4.4]])],

            ['name' => 'Buckshot Roulette', 'image' => 'images/buckshot_roulette.jpg', 'description' => 'Feszült játék élettel-halállal.', 'platform' => 'PC', 'genre' => 'Indie', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Mike Klubnika', 'price' => 499, 'rating' => 4.5]])],
            ['name' => 'Call of Duty: Black Ops 6', 'image' => 'images/cod_black_ops_6.jpg', 'description' => 'Modern taktikai shooter.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2024, 'prices' => json_encode([['seller' => 'Activision', 'price' => 6999, 'rating' => 4.3]])],
            ['name' => 'Call of Duty: Black Ops 7', 'image' => 'images/cod_black_ops_7.png', 'description' => 'A Black Ops sorozat új része.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2025, 'prices' => json_encode([['seller' => 'Activision', 'price' => 6999, 'rating' => 4.3]])],
            ['name' => 'Call of Duty: Modern Warfare 2', 'image' => 'images/cod_modern_warfare_2.jpg', 'description' => 'Modern Warfare újragondolva.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'Activision', 'price' => 5999, 'rating' => 4.5]])],
            ['name' => 'Diablo 3 Xbox', 'image' => 'images/diablo_3_xbox.jpg', 'description' => 'Akció RPG démonok ellen Xbox-on.', 'platform' => 'Xbox', 'genre' => 'RPG', 'category' => 'console_games', 'release_year' => 2013, 'prices' => json_encode([['seller' => 'Blizzard', 'price' => 2999, 'rating' => 4.6]])],
            ['name' => 'Diablo 4 Xbox', 'image' => 'images/diablo_4_xbox.jpg', 'description' => 'Diablo sorozat új része Xbox-on.', 'platform' => 'Xbox', 'genre' => 'RPG', 'category' => 'console_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Blizzard', 'price' => 4999, 'rating' => 4.7]])],
            ['name' => 'DiRT Rally', 'image' => 'images/dirt_rally.jpg', 'description' => 'Rali verseny játék.', 'platform' => 'PC', 'genre' => 'Racing', 'category' => 'pc_games', 'release_year' => 2015, 'prices' => json_encode([['seller' => 'Codemasters', 'price' => 2999, 'rating' => 4.4]])],
            ['name' => 'DiRT Rally 2.0', 'image' => 'images/dirt_rally_2.jpg', 'description' => 'Fejlett rali szimulátor.', 'platform' => 'PC', 'genre' => 'Racing', 'category' => 'pc_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => 'Codemasters', 'price' => 3999, 'rating' => 4.5]])],
            ['name' => 'Elden Ring', 'image' => 'images/elden_ring.jpg', 'description' => 'Open-world akció RPG.', 'platform' => 'PC', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'FromSoftware', 'price' => 5999, 'rating' => 4.9]])],
            ['name' => 'The Forest', 'image' => 'images/forest.jpg', 'description' => 'Túlélő horror játék egy szigeten.', 'platform' => 'PC', 'genre' => 'Survival', 'category' => 'pc_games', 'release_year' => 2018, 'prices' => json_encode([['seller' => 'Endnight Games', 'price' => 1999, 'rating' => 4.3]])],
            ['name' => 'God of War Ragnarök', 'image' => 'images/gow_ragnarök.jpg', 'description' => 'Mitológiai akció játék.', 'platform' => 'PC', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'Santa Monica', 'price' => 6999, 'rating' => 4.8]])],
            ['name' => 'Green Hell', 'image' => 'images/green_hell.jpg', 'description' => 'Túlélő játék az amazóniai dzsungelben.', 'platform' => 'PC', 'genre' => 'Survival', 'category' => 'pc_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => 'Creepy Jar', 'price' => 2999, 'rating' => 4.2]])],
            ['name' => 'Hogwarts Legacy', 'image' => 'images/hogwarts_legacy.jpg', 'description' => 'Harry Potter világában játszódó RPG.', 'platform' => 'PC', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Avalanche Software', 'price' => 5999, 'rating' => 4.6]])],
            ['name' => 'Left 4 Dead', 'image' => 'images/left_4_dead.jpg', 'description' => 'Kooperatív zombie shooter.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2008, 'prices' => json_encode([['seller' => 'Valve', 'price' => 1999, 'rating' => 4.7]])],
            ['name' => 'Left 4 Dead 2', 'image' => 'images/left_4_dead_2.jpg', 'description' => 'A folytatás zombik ellen.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2009, 'prices' => json_encode([['seller' => 'Valve', 'price' => 1999, 'rating' => 4.8]])],
            ['name' => 'Metro Exodus', 'image' => 'images/metro_exodus.jpg', 'description' => 'Poszt-apokaliptikus shooter.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => '4A Games', 'price' => 3999, 'rating' => 4.5]])],
            ['name' => 'Metro Redux', 'image' => 'images/metro_redux.jpg', 'description' => 'A Metro sorozat újrakiadása.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2014, 'prices' => json_encode([['seller' => '4A Games', 'price' => 2999, 'rating' => 4.6]])],
            ['name' => 'Microsoft Office 365', 'image' => 'images/microsoft_office_365.jpg', 'description' => 'Irodai szoftvercsomag előfizetéssel.', 'platform' => 'PC', 'genre' => 'Productivity', 'category' => 'software', 'release_year' => 2011, 'prices' => json_encode([['seller' => 'Microsoft', 'price' => 9999, 'rating' => 4.7]])],
            ['name' => 'Mortal Kombat 11', 'image' => 'images/mortal_kombat_11.jpg', 'description' => 'Harcművészeti játék brutális harcokkal.', 'platform' => 'PC', 'genre' => 'Fighting', 'category' => 'pc_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => 'NetherRealm', 'price' => 3999, 'rating' => 4.4]])],
            ['name' => 'NBA 2K24', 'image' => 'images/nba_2k24.jpg', 'description' => 'Kosárlabda szimulátor.', 'platform' => 'PC', 'genre' => 'Sports', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => '2K Sports', 'price' => 5999, 'rating' => 4.3]])],
            ['name' => 'Need for Speed Heat', 'image' => 'images/need_for_speed_heat.jpg', 'description' => 'Verseny játék autóközponttal.', 'platform' => 'PC', 'genre' => 'Racing', 'category' => 'pc_games', 'release_year' => 1994, 'prices' => json_encode([['seller' => 'EA', 'price' => 2999, 'rating' => 4.2]])],
            ['name' => 'Norton Antivirus', 'image' => 'images/Norton.jpg', 'description' => 'Vírusvédelmi szoftver.', 'platform' => 'PC', 'genre' => 'Security', 'category' => 'software', 'release_year' => 1991, 'prices' => json_encode([['seller' => 'NortonLifeLock', 'price' => 4999, 'rating' => 4.5]])],
            ['name' => 'Outlast 2', 'image' => 'images/outlast_2.jpg', 'description' => 'Horror játék túléléssel.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2017, 'prices' => json_encode([['seller' => 'Red Barrels', 'price' => 2499, 'rating' => 4.1]])],
            ['name' => 'Predator: Hunting Grounds', 'image' => 'images/predator_hunting_grounds.jpg', 'description' => 'Aszimmetrikus multiplayer játék.', 'platform' => 'PC', 'genre' => 'Action', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'IllFonic', 'price' => 2999, 'rating' => 3.8]])],
            ['name' => 'Ready or Not', 'image' => 'images/ready_or_not.jpg', 'description' => 'Taktikai shooter rendőrökként.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => 'VOID Interactive', 'price' => 3999, 'rating' => 4.4]])],
            ['name' => 'Red Dead Redemption', 'image' => 'images/red_dead_redemtion', 'description' => 'Western akció játék.', 'platform' => 'PC', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2010, 'prices' => json_encode([['seller' => 'Rockstar', 'price' => 3999, 'rating' => 4.7]])],
            ['name' => 'Resident Evil', 'image' => 'images/resident_evil.jpg', 'description' => 'Horror játék zombikkal.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 1996, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 1999, 'rating' => 4.6]])],
            ['name' => 'Resident Evil 2', 'image' => 'images/resident_evil_2.jpg', 'description' => 'Újragondolt klasszikus horror.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 3999, 'rating' => 4.8]])],
            ['name' => 'Resident Evil 2 Xbox', 'image' => 'images/resident_evil_2_xbox.jpg', 'description' => 'Horror játék Xbox-on.', 'platform' => 'Xbox', 'genre' => 'Horror', 'category' => 'console_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 3999, 'rating' => 4.8]])],
            ['name' => 'Resident Evil 3', 'image' => 'images/resident_evil_3.jpg', 'description' => 'Akció horror játék.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 3999, 'rating' => 4.7]])],
            ['name' => 'Resident Evil 4', 'image' => 'images/resident_evil_4.jpg', 'description' => 'Akció horror klasszikus.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2005, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 2999, 'rating' => 4.9]])],
            ['name' => 'Resident Evil 4 PS5', 'image' => 'images/resident_evil_4_ps5.jpg', 'description' => 'Remasterelt verzió PS5-ön.', 'platform' => 'PlayStation', 'genre' => 'Horror', 'category' => 'console_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 4999, 'rating' => 4.9]])],
            ['name' => 'Resident Evil Requiem', 'image' => 'images/resident_evil_requiem.jpg', 'description' => 'A sorozat epizódja.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2008, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 1999, 'rating' => 4.2]])],
            ['name' => 'Resident Evil Resistance PS4', 'image' => 'images/resident_evil_resistance_ps4.jpg', 'description' => 'Aszimmetrikus horror PS4-ön.', 'platform' => 'PlayStation', 'genre' => 'Horror', 'category' => 'console_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 3999, 'rating' => 4.3]])],
            ['name' => 'Resident Evil Village', 'image' => 'images/resident_evil_village.png', 'description' => 'Horror játék egy faluban.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2021, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 4999, 'rating' => 4.7]])],
            ['name' => 'Resident Evil Village PS5', 'image' => 'images/resident_evil_village_ps5.jpg', 'description' => 'PS5 verzió.', 'platform' => 'PlayStation', 'genre' => 'Horror', 'category' => 'console_games', 'release_year' => 2021, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 4999, 'rating' => 4.7]])],
            ['name' => 'Resident Evil Village Xbox', 'image' => 'images/resident_evil_village_xbox.jpg', 'description' => 'Xbox verzió.', 'platform' => 'Xbox', 'genre' => 'Horror', 'category' => 'console_games', 'release_year' => 2021, 'prices' => json_encode([['seller' => 'Capcom', 'price' => 4999, 'rating' => 4.7]])],
            ['name' => 'Silent Hill 2', 'image' => 'images/silent_hill_2.jpg', 'description' => 'Pszichológiai horror játék.', 'platform' => 'PC', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2001, 'prices' => json_encode([['seller' => 'Konami', 'price' => 2999, 'rating' => 4.8]])],
            ['name' => 'Spider-Man', 'image' => 'images/spiderman.jpg', 'description' => 'Pókember akció játék.', 'platform' => 'PC', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2018, 'prices' => json_encode([['seller' => 'Insomniac', 'price' => 4999, 'rating' => 4.6]])],
            ['name' => 'Spider-Man 2', 'image' => 'images/spiderman_2.jpg', 'description' => 'A folytatás New Yorkban.', 'platform' => 'PC', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Insomniac', 'price' => 6999, 'rating' => 4.8]])],
            ['name' => 'The Last of Us Part 1 PS5', 'image' => 'images/the_last_of_us_part_1_ps5.jpg', 'description' => 'Remasterelt verzió PS5-ön.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'Naughty Dog', 'price' => 4999, 'rating' => 4.9]])],
            ['name' => 'The Last of Us Part 2', 'image' => 'images/the_last_of_us_part_2.jpg', 'description' => 'A történet folytatása.', 'platform' => 'PC', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Naughty Dog', 'price' => 4999, 'rating' => 4.8]])],
            ['name' => 'The Last of Us Part 2 PS5', 'image' => 'images/the_last_of_us_part_2_ps5.jpg', 'description' => 'PS5 verzió.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Naughty Dog', 'price' => 4999, 'rating' => 4.8]])],








        ];
    }
}
