<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = $this->getProducts();

        foreach ($products as $product) {
            Product::create($product);
        }
    }

    private function getProducts(): array
    {
        return [
            ['name' => 'Call of Duty WW2', 'image' => 'images/cod_ww2.jpg', 'description' => 'Tapasztald meg a második világháború ikonikus csatáit ebben az epikus first-person shooter játékban. Játszd el a híres hadműveleteket és alakítsd a történelem menetét.', 'platform' => 'PC/Console', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2017, 'prices' => json_encode([['seller' => 'GameShop', 'price' => 15999, 'rating' => 4.8], ['seller' => 'DigitalGames', 'price' => 16200, 'rating' => 4.5], ['seller' => 'TechStore', 'price' => 15800, 'rating' => 4.7]])],
            ['name' => 'Dead by Daylight', 'image' => 'images/dbd.jpg', 'description' => 'Egy multiplayer horror játék, ahol túlélők próbálnak megszökni egy gyilkos elől. Játszd a túlélő vagy a gyilkos szerepét izgalmas, feszült mérkőzésekben.', 'platform' => 'Multiplatform', 'genre' => 'Horror', 'category' => 'pc_games', 'release_year' => 2016, 'prices' => json_encode([['seller' => 'HorrorHub', 'price' => 19999, 'rating' => 4.6], ['seller' => 'GameWorld', 'price' => 20100, 'rating' => 4.4], ['seller' => 'DigitalGames', 'price' => 19800, 'rating' => 4.9]])],
            ['name' => 'The Last of Us Part I', 'image' => 'images/lou_part1.jpg', 'description' => 'Joel és Ellie története egy poszt-apokaliptikus világban. Ez az érzelmes, akciódús játék a túlélésről és az emberi kapcsolatokról szól.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2013, 'prices' => json_encode([['seller' => 'SonyStore', 'price' => 8999, 'rating' => 4.9], ['seller' => 'GameShop', 'price' => 9200, 'rating' => 4.7], ['seller' => 'TechStore', 'price' => 8800, 'rating' => 4.8]])],
            ['name' => 'Battlefield 6', 'image' => 'images/bf_6.jpg', 'description' => 'A Battlefield sorozat legújabb része hatalmas, pusztító csatákkal. Tapasztald meg a modern háború káoszát nagy létszámú multiplayer módokban.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2021, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 3999, 'rating' => 4.5], ['seller' => 'GameWorld', 'price' => 4100, 'rating' => 4.3], ['seller' => 'DigitalGames', 'price' => 3950, 'rating' => 4.6]])],
            ['name' => 'FC 26', 'image' => 'images/fc_26.jpg', 'description' => 'A FIFA sorozat új kiadása, ahol irányíthatod kedvenc csapataidat vagy létrehozhatsz saját játékost. Élvezd a valósághű focit 1 hónapos előfizetéssel.', 'platform' => 'Multiplatform', 'genre' => 'Sports', 'category' => 'game_subscriptions', 'release_year' => 2025, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 3500, 'rating' => 4.7], ['seller' => 'SportGames', 'price' => 3600, 'rating' => 4.4], ['seller' => 'GameShop', 'price' => 3450, 'rating' => 4.8]])],
            ['name' => 'Red Dead Redemption 2', 'image' => 'images/rdr_2.jpg', 'description' => 'Arthur Morgan kalandjai az amerikai vadnyugaton. Ez az open-world játék a bűnözés, a túlélés és a moralitás témáit járja körül.', 'platform' => 'Multiplatform', 'genre' => 'Action-Adventure', 'category' => 'game_subscriptions', 'release_year' => 2018, 'prices' => json_encode([['seller' => 'Rockstar Store', 'price' => 4999, 'rating' => 4.9], ['seller' => 'GameWorld', 'price' => 5100, 'rating' => 4.6], ['seller' => 'DigitalGames', 'price' => 4950, 'rating' => 4.8]])],
            ['name' => 'YouCam', 'image' => 'images/youcam.jpg', 'description' => 'Professzionális fényképszerkesztő szoftver. Szépítsd ki képeidet, távolítsd el a háttért és alkosd meg a tökéletes selfie-t.', 'platform' => 'PC', 'genre' => 'Software', 'category' => 'software', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'CyberLink', 'price' => 12999, 'rating' => 4.5], ['seller' => 'SoftwareHub', 'price' => 13200, 'rating' => 4.3], ['seller' => 'TechStore', 'price' => 12800, 'rating' => 4.7]])],
            ['name' => 'McAfee', 'image' => 'images/mcafee.jpg', 'description' => 'Biztonságos vírusvédelmi szoftver. Védje számítógépét a vírusoktól, malware-tól és online fenyegetésektől 1 évig.', 'platform' => 'PC', 'genre' => 'Security', 'category' => 'software', 'release_year' => 2024, 'prices' => json_encode([['seller' => 'McAfee Official', 'price' => 9999, 'rating' => 4.6], ['seller' => 'SecurityPro', 'price' => 10100, 'rating' => 4.4], ['seller' => 'TechStore', 'price' => 9800, 'rating' => 4.8]])],
            ['name' => 'Backup', 'image' => 'images/backup.jpg', 'description' => 'Automatikus adatmentő szoftver. Biztosítsd adataidat a veszteség ellen és tárold őket biztonságosan a felhőben.', 'platform' => 'PC', 'genre' => 'Utility', 'category' => 'software', 'release_year' => 2024, 'prices' => json_encode([['seller' => 'Backup Solutions', 'price' => 2999, 'rating' => 4.4], ['seller' => 'SoftwareHub', 'price' => 3100, 'rating' => 4.2], ['seller' => 'TechStore', 'price' => 2950, 'rating' => 4.6]])],
            ['name' => 'Grand Theft Auto V', 'image' => 'images/gta_v.jpg', 'description' => 'Los Santos városában játszódó open-world akció játék. Lopj autót, kövess el bűncselekményeket és élvezd a szabadságot.', 'platform' => 'Multiplatform', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2013, 'prices' => json_encode([['seller' => 'Rockstar Store', 'price' => 2999, 'rating' => 4.8], ['seller' => 'GameWorld', 'price' => 3100, 'rating' => 4.6], ['seller' => 'DigitalGames', 'price' => 2950, 'rating' => 4.9]])],
            ['name' => 'Minecraft', 'image' => 'images/minecraft.jpg', 'description' => 'Kreatív sandbox játék, ahol építhetsz, bányászolhatsz és túlélhetsz egy blokkos világban. Végtelen lehetőségek.', 'platform' => 'Multiplatform', 'genre' => 'Sandbox', 'category' => 'pc_games', 'release_year' => 2011, 'prices' => json_encode([['seller' => 'Mojang', 'price' => 4999, 'rating' => 4.7], ['seller' => 'GameShop', 'price' => 5100, 'rating' => 4.5], ['seller' => 'DigitalGames', 'price' => 4950, 'rating' => 4.8]])],
            ['name' => 'Fortnite', 'image' => 'images/fortnite.jpg', 'description' => 'Battle Royale játék, ahol 100 játékos harcol egymással egy szigeten. Építs, lőj és legyél az utolsó túlélő.', 'platform' => 'Multiplatform', 'genre' => 'Battle Royale', 'category' => 'pc_games', 'release_year' => 2017, 'prices' => json_encode([['seller' => 'Epic Games', 'price' => 0, 'rating' => 4.4], ['seller' => 'GameWorld', 'price' => 0, 'rating' => 4.2]])],
            ['name' => 'The Witcher 3: Wild Hunt', 'image' => 'images/witcher3.jpg', 'description' => 'Geralt of Rivia kalandjai egy fantasy világban. Vadászd a szörnyeket, hozd meg a nehéz döntéseket.', 'platform' => 'Multiplatform', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2015, 'prices' => json_encode([['seller' => 'CD Projekt', 'price' => 1999, 'rating' => 4.9], ['seller' => 'GameShop', 'price' => 2100, 'rating' => 4.7], ['seller' => 'DigitalGames', 'price' => 1950, 'rating' => 4.8]])],
            ['name' => 'Cyberpunk 2077', 'image' => 'images/cyberpunk2077.jpg', 'description' => 'Night City-ben játszódó RPG, ahol a jövőben élsz. Válassz utadat a bűnözők, vállalatok és hackerek világában.', 'platform' => 'Multiplatform', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'CD Projekt', 'price' => 3999, 'rating' => 4.2], ['seller' => 'GameWorld', 'price' => 4100, 'rating' => 4.0], ['seller' => 'DigitalGames', 'price' => 3950, 'rating' => 4.3]])],
            ['name' => 'Among Us', 'image' => 'images/amongus.jpg', 'description' => 'Multiplayer játék, ahol űrhajósok között vannak imposterok. Találd ki ki a csaló és mentsd meg a hajót.', 'platform' => 'Multiplatform', 'genre' => 'Party', 'category' => 'pc_games', 'release_year' => 2018, 'prices' => json_encode([['seller' => 'Innersloth', 'price' => 499, 'rating' => 4.5], ['seller' => 'GameShop', 'price' => 600, 'rating' => 4.3]])],
            ['name' => 'League of Legends', 'image' => 'images/lol.jpg', 'description' => 'MOBA játék, ahol két csapat harcol egymással. Válassz hőst és győzd le az ellenséget.', 'platform' => 'PC', 'genre' => 'MOBA', 'category' => 'pc_games', 'release_year' => 2009, 'prices' => json_encode([['seller' => 'Riot Games', 'price' => 0, 'rating' => 4.6]])],
            ['name' => 'Valorant', 'image' => 'images/valorant.jpg', 'description' => 'Taktikai FPS játék, ahol ügynökök harcolnak. Használj képességeket és stratégiát a győzelemért.', 'platform' => 'PC', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Riot Games', 'price' => 0, 'rating' => 4.7]])],
            ['name' => 'Apex Legends', 'image' => 'images/apex.jpg', 'description' => 'Battle Royale játék, ahol legendák harcolnak. Válassz karaktert és használd egyedi képességeiket.', 'platform' => 'Multiplatform', 'genre' => 'Battle Royale', 'category' => 'pc_games', 'release_year' => 2019, 'prices' => json_encode([['seller' => 'Respawn', 'price' => 0, 'rating' => 4.5]])],
            ['name' => 'Overwatch 2', 'image' => 'images/overwatch2.jpg', 'description' => 'Team-based shooter, ahol hősök harcolnak. Válassz szerepet és segítsd csapatod győzelmét.', 'platform' => 'Multiplatform', 'genre' => 'FPS', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'Blizzard', 'price' => 0, 'rating' => 4.4]])],
            ['name' => 'World of Warcraft', 'image' => 'images/wow.jpg', 'description' => 'MMORPG játék Azeroth világában. Kalandozz, harcolj és építs karaktert.', 'platform' => 'PC', 'genre' => 'MMORPG', 'category' => 'pc_games', 'release_year' => 2004, 'prices' => json_encode([['seller' => 'Blizzard', 'price' => 1499, 'rating' => 4.3]])],
            ['name' => 'The Sims 4', 'image' => 'images/sims4.jpg', 'description' => 'Életszimulátor játék, ahol irányítod a simsek életét. Építs házat, neveld az állatokat és építs karriert.', 'platform' => 'PC', 'genre' => 'Simulation', 'category' => 'pc_games', 'release_year' => 2014, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 1999, 'rating' => 4.5], ['seller' => 'GameShop', 'price' => 2100, 'rating' => 4.3]])],
            ['name' => 'Stardew Valley', 'image' => 'images/stardew.jpg', 'description' => 'Farm szimulátor játék. Műveld a földet, neveld az állatokat és építs kapcsolatokat.', 'platform' => 'Multiplatform', 'genre' => 'Simulation', 'category' => 'pc_games', 'release_year' => 2016, 'prices' => json_encode([['seller' => 'ConcernedApe', 'price' => 1499, 'rating' => 4.8], ['seller' => 'GameWorld', 'price' => 1600, 'rating' => 4.6]])],
            ['name' => 'Civilization VI', 'image' => 'images/civ6.jpg', 'description' => 'Stratégiai játék, ahol civilizációt építesz az ókortól a modern korig.', 'platform' => 'Multiplatform', 'genre' => 'Strategy', 'category' => 'pc_games', 'release_year' => 2016, 'prices' => json_encode([['seller' => '2K Games', 'price' => 2999, 'rating' => 4.7], ['seller' => 'GameShop', 'price' => 3100, 'rating' => 4.5]])],
            ['name' => 'FIFA 23', 'image' => 'images/fifa23.jpg', 'description' => 'Foci szimulátor játék. Játszd a mérkőzéseket, irányítsd a csapatokat.', 'platform' => 'Multiplatform', 'genre' => 'Sports', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'EA Store', 'price' => 4999, 'rating' => 4.4], ['seller' => 'SportGames', 'price' => 5100, 'rating' => 4.2]])],
            ['name' => 'NBA 2K24', 'image' => 'images/nba2k24.jpg', 'description' => 'Kosárlabda szimulátor. Játszd a NBA mérkőzéseket, építs csapatot.', 'platform' => 'Multiplatform', 'genre' => 'Sports', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => '2K Games', 'price' => 5999, 'rating' => 4.6], ['seller' => 'SportGames', 'price' => 6100, 'rating' => 4.4]])],
            ['name' => 'Assassin\'s Creed Valhalla', 'image' => 'images/ac_valhalla.jpg', 'description' => 'Viking kalandok Angliában. Harcolj, építs települést és fedezd fel a történelmet.', 'platform' => 'Multiplatform', 'genre' => 'Action-Adventure', 'category' => 'pc_games', 'release_year' => 2020, 'prices' => json_encode([['seller' => 'Ubisoft', 'price' => 3999, 'rating' => 4.5], ['seller' => 'GameWorld', 'price' => 4100, 'rating' => 4.3]])],
            ['name' => 'Spider-Man 2', 'image' => 'images/spiderman2.jpg', 'description' => 'Peter Parker és Miles Morales kalandjai New Yorkban. Harcolj a bűnözők ellen.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'SonyStore', 'price' => 6999, 'rating' => 4.8], ['seller' => 'GameShop', 'price' => 7100, 'rating' => 4.6]])],
            ['name' => 'Hogwarts Legacy', 'image' => 'images/hogwarts.jpg', 'description' => 'Harry Potter világában játszódó RPG. Tanulj varázslatot, fedezd fel a kastélyt.', 'platform' => 'Multiplatform', 'genre' => 'RPG', 'category' => 'pc_games', 'release_year' => 2023, 'prices' => json_encode([['seller' => 'Warner Bros', 'price' => 4999, 'rating' => 4.7], ['seller' => 'GameWorld', 'price' => 5100, 'rating' => 4.5]])],
            ['name' => 'Elden Ring', 'image' => 'images/elden_ring.jpg', 'description' => 'Dark Souls stílusú akció RPG. Harcolj szörnyekkel, fedezd fel a világot.', 'platform' => 'Multiplatform', 'genre' => 'Action RPG', 'category' => 'pc_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'Bandai Namco', 'price' => 5999, 'rating' => 4.9], ['seller' => 'GameShop', 'price' => 6100, 'rating' => 4.7]])],
            ['name' => 'God of War Ragnarök', 'image' => 'images/gow_ragnarok.jpg', 'description' => 'Kratos és Atreus kalandjai a skandináv mitológiában. Epikus történet és harc.', 'platform' => 'PlayStation', 'genre' => 'Action-Adventure', 'category' => 'console_games', 'release_year' => 2022, 'prices' => json_encode([['seller' => 'SonyStore', 'price' => 6999, 'rating' => 4.9], ['seller' => 'GameWorld', 'price' => 7100, 'rating' => 4.7]])],
            ['name' => 'Adobe Photoshop', 'image' => 'images/photoshop.jpg', 'description' => 'Professzionális képszerkesztő szoftver. Szerkessz fényképeket, tervezz grafikát.', 'platform' => 'PC', 'genre' => 'Software', 'category' => 'software', 'release_year' => 1990, 'prices' => json_encode([['seller' => 'Adobe', 'price' => 23999, 'rating' => 4.8]])],
            ['name' => 'Microsoft Office 365', 'image' => 'images/office365.jpg', 'description' => 'Irodai szoftvercsomag. Word, Excel, PowerPoint és több.', 'platform' => 'PC', 'genre' => 'Software', 'category' => 'software', 'release_year' => 2011, 'prices' => json_encode([['seller' => 'Microsoft', 'price' => 9999, 'rating' => 4.6]])],
            ['name' => 'Norton Antivirus', 'image' => 'images/norton.jpg', 'description' => 'Vírusvédelmi szoftver. Védelmet nyújt vírusok és online fenyegetések ellen.', 'platform' => 'PC', 'genre' => 'Security', 'category' => 'software', 'release_year' => 1991, 'prices' => json_encode([['seller' => 'Norton', 'price' => 4999, 'rating' => 4.5], ['seller' => 'SecurityPro', 'price' => 5100, 'rating' => 4.3]])],
            ['name' => 'WinRAR', 'image' => 'images/winrar.jpg', 'description' => 'Fájltömörítő szoftver. Tömörítsd és bontsd ki a fájlokat.', 'platform' => 'PC', 'genre' => 'Utility', 'category' => 'software', 'release_year' => 1995, 'prices' => json_encode([['seller' => 'WinRAR GmbH', 'price' => 2999, 'rating' => 4.4], ['seller' => 'SoftwareHub', 'price' => 3100, 'rating' => 4.2]])],
            ['name' => 'CCleaner', 'image' => 'images/ccleaner.jpg', 'description' => 'Rendszerkarbantartó szoftver. Tisztítsd meg a számítógépet a felesleges fájloktól.', 'platform' => 'PC', 'genre' => 'Utility', 'category' => 'software', 'release_year' => 2004, 'prices' => json_encode([['seller' => 'Piriform', 'price' => 1999, 'rating' => 4.3], ['seller' => 'TechStore', 'price' => 2100, 'rating' => 4.1]])],
            ['name' => 'Zoom', 'image' => 'images/zoom.jpg', 'description' => 'Videokonferencia szoftver. Tartson online találkozókat és webinarokat.', 'platform' => 'Multiplatform', 'genre' => 'Communication', 'category' => 'software', 'release_year' => 2011, 'prices' => json_encode([['seller' => 'Zoom', 'price' => 0, 'rating' => 4.2]])],
            ['name' => 'Slack', 'image' => 'images/slack.jpg', 'description' => 'Csapatkommunikációs eszköz. Csevegés, fájlmegosztás és együttműködés.', 'platform' => 'Multiplatform', 'genre' => 'Communication', 'category' => 'software', 'release_year' => 2013, 'prices' => json_encode([['seller' => 'Slack', 'price' => 0, 'rating' => 4.5]])],
            ['name' => 'Discord', 'image' => 'images/discord.jpg', 'description' => 'Hang- és szövegkommunikációs alkalmazás játékosok számára.', 'platform' => 'Multiplatform', 'genre' => 'Communication', 'category' => 'software', 'release_year' => 2015, 'prices' => json_encode([['seller' => 'Discord', 'price' => 0, 'rating' => 4.6]])],
            ['name' => 'Spotify Premium', 'image' => 'images/spotify.jpg', 'description' => 'Zenei streaming szolgáltatás. Hallgass millió zenét reklámmentesen.', 'platform' => 'Multiplatform', 'genre' => 'Entertainment', 'category' => 'software', 'release_year' => 2008, 'prices' => json_encode([['seller' => 'Spotify', 'price' => 999, 'rating' => 4.7]])],
            ['name' => 'Netflix', 'image' => 'images/netflix.jpg', 'description' => 'Videostreaming szolgáltatás. Nézz filmeket és sorozatokat.', 'platform' => 'Multiplatform', 'genre' => 'Entertainment', 'category' => 'software', 'release_year' => 2007, 'prices' => json_encode([['seller' => 'Netflix', 'price' => 1499, 'rating' => 4.5]])],
            ['name' => 'Amazon Prime Video', 'image' => 'images/prime_video.jpg', 'description' => 'Videostreaming szolgáltatás. Nézz exkluzív tartalmakat.', 'platform' => 'Multiplatform', 'genre' => 'Entertainment', 'category' => 'software', 'release_year' => 2006, 'prices' => json_encode([['seller' => 'Amazon', 'price' => 999, 'rating' => 4.4]])],
            ['name' => 'YouTube Premium', 'image' => 'images/youtube_premium.jpg', 'description' => 'Videómegosztó szolgáltatás prémium verziója. Reklámmentes nézés.', 'platform' => 'Multiplatform', 'genre' => 'Entertainment', 'category' => 'software', 'release_year' => 2014, 'prices' => json_encode([['seller' => 'Google', 'price' => 1399, 'rating' => 4.3]])],
            ['name' => 'Canva Pro', 'image' => 'images/canva.jpg', 'description' => 'Grafikai tervező eszköz. Készíts posztereket, prezentációkat.', 'platform' => 'Web', 'genre' => 'Design', 'category' => 'software', 'release_year' => 2012, 'prices' => json_encode([['seller' => 'Canva', 'price' => 1299, 'rating' => 4.6]])],
            ['name' => 'Grammarly Premium', 'image' => 'images/grammarly.jpg', 'description' => 'Írásjavító eszköz. Ellenőrizd helyesírásod és stílusod.', 'platform' => 'Web', 'genre' => 'Writing', 'category' => 'software', 'release_year' => 2009, 'prices' => json_encode([['seller' => 'Grammarly', 'price' => 2999, 'rating' => 4.5]])],
            ['name' => 'Evernote Premium', 'image' => 'images/evernote.jpg', 'description' => 'Jegyzetkezelő alkalmazás. Szervezd jegyzeteidet és emlékeztetőidet.', 'platform' => 'Multiplatform', 'genre' => 'Productivity', 'category' => 'software', 'release_year' => 2008, 'prices' => json_encode([['seller' => 'Evernote', 'price' => 4999, 'rating' => 4.4]])],
            ['name' => 'Trello', 'image' => 'images/trello.jpg', 'description' => 'Projektmenedzsment eszköz. Szervezd feladataidat kártyákban.', 'platform' => 'Web', 'genre' => 'Productivity', 'category' => 'software', 'release_year' => 2011, 'prices' => json_encode([['seller' => 'Atlassian', 'price' => 0, 'rating' => 4.5]])],
            ['name' => 'Asana', 'image' => 'images/asana.jpg', 'description' => 'Feladatkezelő alkalmazás. Kezeld projekteket és csapatmunkát.', 'platform' => 'Multiplatform', 'genre' => 'Productivity', 'category' => 'software', 'release_year' => 2008, 'prices' => json_encode([['seller' => 'Asana', 'price' => 0, 'rating' => 4.3]])],
            ['name' => 'Dropbox', 'image' => 'images/dropbox.jpg', 'description' => 'Felhőtároló szolgáltatás. Tárold és oszd meg fájljaidat.', 'platform' => 'Multiplatform', 'genre' => 'Storage', 'category' => 'software', 'release_year' => 2008, 'prices' => json_encode([['seller' => 'Dropbox', 'price' => 999, 'rating' => 4.4]])],
            ['name' => 'Google Drive', 'image' => 'images/gdrive.jpg', 'description' => 'Felhőteroló szolgáltatás. Ingyenes tárhely és együttműködés.', 'platform' => 'Web', 'genre' => 'Storage', 'category' => 'software', 'release_year' => 2012, 'prices' => json_encode([['seller' => 'Google', 'price' => 199, 'rating' => 4.6]])],
            ['name' => 'OneDrive', 'image' => 'images/onedrive.jpg', 'description' => 'Microsoft felhőtárolóslgáltatás. Integrálva az Office-szal.', 'platform' => 'Multiplatform', 'genre' => 'Storage', 'category' => 'software', 'release_year' => 2007, 'prices' => json_encode([['seller' => 'Microsoft', 'price' => 699, 'rating' => 4.5]])],
        ];
    }
}
